# This workflow will upload a Vscode Package to Visual Studio Market when a release is created.

name: Publish Wednesday Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Wednesday
        uses: actions/checkout@v5

      - name: Setup/Install Nodes
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

  vsce-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build

    steps:
      - name: Install Wednesday Dependencies
        run: npm install
      - name: Publish Wednesday Distribution
        env:
          VSCE_PUBLISHER_TOKEN: ${{ secrets.VSCE_PUBLISHER_TOKEN }}
        run: npm run vsce-publish -- -p $VSCE_PUBLISHER_TOKEN
